[credentials]
username = 'Homer.Simpson'
password = 'do.it.for.her'

[options]
project = 'Springfield Nuclear Power Plant'
category = 'Development'
description = 'Features development'
focal = 'Mr. Burns'
hours = 6